# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import magi.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('majilove', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiblePhoto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('_cache_account_last_update', models.DateTimeField(null=True)),
                ('_cache_j_account', models.TextField(null=True)),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Level')),
                ('leader_bonus', models.PositiveIntegerField(null=True, verbose_name='Leader skill percentage')),
                ('skill_level', models.PositiveIntegerField(default=1, verbose_name='Skill level')),
                ('sub_skill_level', models.PositiveIntegerField(null=True, verbose_name='Sub skill level')),
                ('rank', models.PositiveIntegerField(default=1, verbose_name='Rank')),
                ('moments_unlocked', models.PositiveIntegerField(default=0, verbose_name='Percent of moments unlocked')),
                ('bonus_moment_squares_unlocked', models.PositiveIntegerField(default=0, verbose_name='Number of moment squares unlocked past 100%')),
                ('prefer_normal_shot', models.BooleanField(default=False, verbose_name='Prefer normal shot photo image')),
                ('i_silver_crown_amount', models.PositiveIntegerField(null=True, verbose_name='Silver crown bonus', choices=[(0, 150), (1, 200)])),
                ('i_silver_crown_attribute', models.PositiveIntegerField(null=True, verbose_name='Silver crown attribute', choices=[(0, 'Dance'), (1, 'Vocal'), (2, 'Charm')])),
                ('i_gold_crown_amount', models.PositiveIntegerField(null=True, verbose_name='Gold crown bonus', choices=[(0, 150), (1, 200)])),
                ('i_gold_crown_attribute', models.PositiveIntegerField(null=True, verbose_name='Gold crown attribute', choices=[(0, 'Dance'), (1, 'Vocal'), (2, 'Charm')])),
                ('i_rainbow_crown_amount', models.PositiveIntegerField(null=True, verbose_name='Rainbow crown bonus', choices=[(0, 150), (1, 200)])),
                ('i_rainbow_crown_attribute', models.PositiveIntegerField(null=True, verbose_name='Rainbow crown attribute', choices=[(0, 'Dance'), (1, 'Vocal'), (2, 'Charm')])),
                ('custom_dance_stat', models.PositiveIntegerField(null=True, verbose_name='Dance')),
                ('custom_vocal_stat', models.PositiveIntegerField(null=True, verbose_name='Vocal')),
                ('custom_charm_stat', models.PositiveIntegerField(null=True, verbose_name='Charm')),
                ('account', models.ForeignKey(related_name='photoscollectors', verbose_name='Account', to='majilove.Account')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(help_text=b'in romaji', unique=True, max_length=100, verbose_name='Name')),
                ('japanese_name', models.CharField(unique=True, max_length=100, verbose_name='Name (Japanese)')),
                ('d_names', models.TextField(null=True, verbose_name='Name')),
                ('i_group', models.PositiveIntegerField(null=True, verbose_name='Group', choices=[(0, 'ST\u2606RISH'), (1, b'QUARTET NIGHT')])),
                ('cv_name', models.CharField(help_text=b'in romaji', max_length=100, null=True, verbose_name='Voice actor')),
                ('japanese_cv_name', models.CharField(max_length=100, null=True, verbose_name='Voice actor (Japanese)')),
                ('d_cv_names', models.TextField(null=True, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Description')),
                ('d_descriptions', models.TextField(null=True, verbose_name='Description')),
                ('height', models.PositiveIntegerField(help_text=b'in cm', null=True, verbose_name='Height')),
                ('weight', models.PositiveIntegerField(help_text=b'in kg', null=True, verbose_name='Weight')),
                ('i_blood_type', models.PositiveIntegerField(null=True, verbose_name='Blood Type', choices=[(0, b'O'), (1, b'A'), (2, b'B'), (3, b'AB'), (4, b'?')])),
                ('birthday', models.DateField(help_text=b'The year is not used, so write whatever', null=True, verbose_name='Birthday')),
                ('i_astrological_sign', models.PositiveIntegerField(null=True, verbose_name='Astrological Sign', choices=[(0, 'Leo'), (1, 'Aries'), (2, 'Libra'), (3, 'Virgo'), (4, 'Scorpio'), (5, 'Capricorn'), (6, 'Pisces'), (7, 'Gemini'), (8, 'Cancer'), (9, 'Sagittarius'), (10, 'Aquarius'), (11, 'Taurus')])),
                ('instrument', models.CharField(max_length=100, null=True, verbose_name='Instrument')),
                ('d_instruments', models.TextField(null=True, verbose_name='Instrument')),
                ('hometown', models.CharField(max_length=100, null=True, verbose_name='Hometown')),
                ('d_hometowns', models.TextField(null=True, verbose_name='Hometown')),
                ('hobby', models.CharField(max_length=100, null=True, verbose_name='Hobby')),
                ('d_hobbys', models.TextField(null=True, verbose_name='Hobby')),
                ('color', models.CharField(help_text=b'Format: #XXXXXX', max_length=7, verbose_name=b'Color')),
                ('image', models.ImageField(upload_to=magi.utils.uploadItem(b'idol'), verbose_name='Image')),
                ('owner', models.ForeignKey(related_name='added_idols', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.PositiveIntegerField(unique=True, serialize=False, verbose_name='Album ID', primary_key=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='Photo name')),
                ('d_names', models.TextField(null=True, verbose_name='Photo name')),
                ('release_date', models.DateField(null=True, verbose_name='Release date', db_index=True)),
                ('image', models.ImageField(upload_to=magi.utils.uploadItem(b'photo'), null=True, verbose_name='Icon')),
                ('image_special_shot', models.ImageField(upload_to=magi.utils.uploadItem(b'photo/specialshot'), null=True, verbose_name='Icon (Special shot)')),
                ('full_photo', models.ImageField(upload_to=magi.utils.uploadItem(b'photo/image'), verbose_name='Photo image')),
                ('full_photo_special_shot', models.ImageField(upload_to=magi.utils.uploadItem(b'photo/image/specialshot'), null=True, verbose_name='Photo image (Special shot)')),
                ('transparent', models.ImageField(upload_to=magi.utils.uploadItem(b'photo/transparent'), null=True, verbose_name='Transparent')),
                ('transparent_special_shot', models.ImageField(upload_to=magi.utils.uploadItem(b'photo/transparent/specialshot'), null=True, verbose_name='Transparent (Special shot)')),
                ('art', models.ImageField(upload_to=magi.utils.uploadItem(b'photo/poster'), null=True, verbose_name='Poster')),
                ('art_special_shot', models.ImageField(upload_to=magi.utils.uploadItem(b'photo/poster/specialshot'), null=True, verbose_name='Poster (Special shot)')),
                ('message', models.ImageField(upload_to=magi.utils.uploadItem(b'photo/message'), null=True, verbose_name='Message')),
                ('autograph', models.ImageField(upload_to=magi.utils.uploadItem(b'photo/autograph'), null=True, verbose_name='Autograph')),
                ('message_text', models.TextField(max_length=500, null=True, verbose_name='Message text (Japanese)')),
                ('message_translation', models.TextField(max_length=500, null=True, verbose_name='Message translation')),
                ('d_message_translations', models.TextField(null=True, verbose_name='Message translation')),
                ('i_rarity', models.PositiveIntegerField(db_index=True, verbose_name='Rarity', choices=[(0, b'N'), (1, b'R'), (2, b'SR'), (3, b'UR')])),
                ('i_color', models.PositiveIntegerField(db_index=True, verbose_name='Color', choices=[(0, 'Star'), (1, 'Shine'), (2, 'Dream')])),
                ('dance_min', models.PositiveIntegerField(default=0, verbose_name='Dance (Minimum)')),
                ('dance_single_copy_max', models.PositiveIntegerField(default=0, verbose_name='Dance (Single copy maximum)')),
                ('dance_max_copy_max', models.PositiveIntegerField(default=0, verbose_name='Dance (Maxed copy maximum)')),
                ('vocal_min', models.PositiveIntegerField(default=0, verbose_name='Vocal (Minimum)')),
                ('vocal_single_copy_max', models.PositiveIntegerField(default=0, verbose_name='Vocal (Single copy maximum)')),
                ('vocal_max_copy_max', models.PositiveIntegerField(default=0, verbose_name='Vocal (Maxed copy maximum)')),
                ('charm_min', models.PositiveIntegerField(default=0, verbose_name='Charm (Minimum)')),
                ('charm_single_copy_max', models.PositiveIntegerField(default=0, verbose_name='Charm (Single copy maximum)')),
                ('charm_max_copy_max', models.PositiveIntegerField(default=0, verbose_name='Charm (Maxed copy maximum)')),
                ('i_leader_skill_stat', models.PositiveIntegerField(null=True, verbose_name=b'{t_leader_skill_stat}', choices=[(0, 'Dance'), (1, 'Vocal'), (2, 'Charm')])),
                ('leader_skill_percentage', models.PositiveIntegerField(null=True, verbose_name=b'{leader_skill_percentage}')),
                ('i_skill_type', models.PositiveIntegerField(db_index=True, null=True, verbose_name='Skill', choices=[(0, 'Score notes'), (1, 'Perfect score up'), (2, 'Cut-in'), (3, 'Good lock'), (4, 'Great lock'), (5, 'Healer')])),
                ('skill_note_count', models.PositiveIntegerField(null=True, verbose_name=b'{skill_note_count}')),
                ('skill_percentage', models.FloatField(null=True, verbose_name=b'{skill_percentage}')),
                ('i_sub_skill_type', models.PositiveIntegerField(null=True, verbose_name='Sub skill', choices=[(0, 'Full combo'), (1, 'Stamina based')])),
                ('sub_skill_amount', models.PositiveIntegerField(null=True, verbose_name=b'{sub_skill_amount}')),
                ('sub_skill_percentage', models.FloatField(null=True, verbose_name=b'{sub_skill_percentage}')),
                ('sub_skill_increment', models.PositiveIntegerField(null=True, verbose_name='Sub skill level up increment')),
                ('_cache_idol_last_update', models.DateTimeField(null=True)),
                ('_cache_j_idol', models.TextField(null=True)),
                ('idol', models.ForeignKey(related_name='photos', verbose_name='Idol', to='majilove.Idol')),
                ('owner', models.ForeignKey(related_name='added_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='collectiblephoto',
            name='photo',
            field=models.ForeignKey(related_name='collectedphotos', verbose_name='Photo', to='majilove.Photo'),
            preserve_default=True,
        ),
    ]
